# no customizing required
samples: "config/samples.tsv"
output_dir: "/vol/spacex/nanopore/test_pipeline/f"
#allfiles: "config/allfiles.tsv"
#experiments: "config/sample_sheet.tsv"
#controlgroup: "config/sample_sheet.tsv"
#path: "config/allfiles.tsv"

#please update with exact modelname and its path in case a new model is used
basecall_model: "/vol/spacex/nanopore/test_pipeline/f/rna004_130bps_hac@v5.1.0"
#how many threads are needed for basecalling
threads: "10"
#for basecaller modified base :
modbase : "m6A_DRACH"
# for basecaller batchsize:
batchsize : "4000"

# for aligner genome location:
genome: "/vol/spacex/nanopore/test_pipeline/f/mm39_fasta/Mus_musculus.GRCm39.cdna.all.fa"
genome_fai: "/vol/spacex/nanopore/test_pipeline/f/mm39_fasta/Mus_musculus.GRCm39.cdna.all.fa.fai"
extract_region: "chr20"

# directories
workdirection : "/vol/spacex/nanopore/test_pipeline/final"
resultdirectory: "results"
end: "s" 